# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: daenkcrewDev
author: daenkcrew   
email: daenkcrew.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a simple man. I do what I want and what I could. Otherwise
  it's a trial and error.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daenkcrew.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username: daenkcrew

# Sosial media
social:
  email: daenkcrew [dot] dev [at] gmail [dot] com
  github:
    username: daenkcrew
    url: https://github.com/daenkcrew
    enabled: true
  gitlab:
    username: daenkcrew
    url: https://gitlab.com/daenkcrew
    enabled: false
  stackoverflow:
    username: daenkcrew
    url: https://stackoverflow.com/users/daenkcrew
    enabled: true
  twitter:
    username: daenkcrew
    url: https://twitter.com/daenkcrew
    enabled: true
  youtube:
    username: daenkcrewDev
    url: https://www.youtube.com/daenkcrew
    enabled: false

# Third party services
disqus:
  shortname: 
google_analytics: UA-xxxxxxxxx-1

# Build settings
defaults:
-
    scope:
      path: ""
      type: "posts"
    values:
      category: "en"
      author: "zackad"
      future: true
markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  style: compressed